

# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
     '#{script}',
     {paths: [process.argv[1]]},
    )", __dir__]).strip
end
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')
 
platform :ios, min_ios_version_supported
prepare_react_native_project!
 
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


  permissions_path = '../node_modules/react-native-permissions/ios'
  setup_permissions([
   'AppTrackingTransparency',
   'Bluetooth',
   'Calendars',
   'CalendarsWriteOnly',
   'Camera',
   'Contacts',
   'FaceID',
   'LocationAccuracy',
   'LocationAlways',
   'LocationWhenInUse',
   'MediaLibrary',
   'Microphone',
   'Motion',
   'Notifications',
   'PhotoLibrary',
   'PhotoLibraryAddOnly',
   'Reminders',
   'Siri',
   'SpeechRecognition',
   'StoreKit',
])

abstract_target 'available_pods' do
  rn_maps_path = '../node_modules/react-native-maps'
  use_frameworks! :linkage => :static
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :new_arch_enabled => false
  )

  # pod 'react-native-google-maps', :path => rn_maps_path
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'
  pod 'ZendeskChatSDK'
  pod 'ZendeskChatProvidersSDK'
  pod 'razorpay-pod', '1.5.0'

  
#JunoRide Target
target 'JunoRide' do
end

post_install do |installer|
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )
  # Patch fmt base.h so externally-defined FMT_USE_CONSTEVAL=0 is not overridden
  # by the library's own detection chain (fmt 11 doesn't guard with #ifndef).
  fmt_base_h = "#{installer.sandbox.root}/fmt/include/fmt/base.h"
  if File.exist?(fmt_base_h)
    content = File.read(fmt_base_h)
    patch_marker = "// [PATCHED] FMT_USE_CONSTEVAL guard"
    unless content.include?(patch_marker)
      old_line = "// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.\n#if !defined(__cpp_lib_is_constant_evaluated)"
      new_line  = "// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.\n" + patch_marker + "\n#ifndef FMT_USE_CONSTEVAL\n#if !defined(__cpp_lib_is_constant_evaluated)"
      content = content.sub(old_line, new_line)
      old_end  = "#if FMT_USE_CONSTEVAL\n#  define FMT_CONSTEVAL consteval"
      new_end  = "#endif  // ifndef FMT_USE_CONSTEVAL\n#if FMT_USE_CONSTEVAL\n#  define FMT_CONSTEVAL consteval"
      content = content.sub(old_end, new_end)
      File.chmod(0644, fmt_base_h)
      File.write(fmt_base_h, content)
    end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
      if target.name == 'fmt'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_USE_CONSTEVAL=0'
      end
    end
  end
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
  installer.pods_project.targets.each do |target|
    if target.name == "React-Core.common-AccessibilityResources"
      target.remove_from_project
    end
  end
end
end

